environment:
    global:
        TWINE_USERNAME:
            secure: AIbDZTVaU3Ijr7mtxW7dlw==
        TWINE_PASSWORD:
            secure: YI+izt+hzh/czFuDCrne4XN78nQmT7jvcqe9uWvndqAUxhyXqr98GJ9FUSVPbqyWx+pW+5cKvh2PMdDEPJUcHMG8dtpHcosn3ndXnHGkHH3mwOnOduiUtrhlSEoIFwbZUhFRScYvfILGD8KM7RgcCiUUcner8QOFPiFX1zey8WVLynIj3c1rVe6Ola18pIUoL9D4NITNt5EWxexvr4vnkHmydk6dzWHBpiGsFujzccg+MoYN2ZjiN2JGSOykmEF/
    matrix:
        - python: 27
        - python: 27-x64
        - python: 35
        - python: 35-x64
        - python: 36
        - python: 36-x64
        - python: 37
        - python: 37-x64
        - python: 38
        - python: 38-x64

install:
    - SET PATH=C:\\Python%PYTHON%;c:\\Python%PYTHON%\\scripts;%PATH%
    - python -m pip.__main__ install -U pip wheel setuptools
    - pip install -r requirements-test.txt

build: off
build_script:
   # configure version
    - ps: >-
        If ($env:APPVEYOR_REPO_TAG -Eq "true" ) {
            $version = "$env:APPVEYOR_REPO_TAG_NAME"
        } Else {
            pip install setuptools-scm
            $version = python -c "from setuptools_scm import get_version; print(get_version())"
        }
        $version | Set-Content version.txt
    - python setup.py --version
    - python setup.py build bdist_wheel
    - ps: Get-ChildItem dist\*.whl | % { pip install $_.FullName }

test: off
test_script:
    - pip list
    - py.test -v tests
    - ps: Get-ChildItem dist\*.whl | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }


deploy: on
deploy_script:
    - ps: >-
        If ($env:APPVEYOR_REPO_TAG -eq $TRUE) {
            pip install twine
            twine upload dist/*.whl
        }
