name: sdist
on: [push, pull_request]
jobs:
  sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install build dependencies
        run: |
          pip install --upgrade pip setuptools wheel
      - name: Package source dist
        run: |
          python setup.py sdist
      - name: Install test dependencies
        env:
          PYXMLSEC_STATIC_DEPS: true
          # disable libxml2-2.9.12 because of https://gitlab.gnome.org/GNOME/libxslt/-/issues/52
          PYXMLSEC_LIBXML2_VERSION: 2.9.10
        run: |
          pip install --upgrade -r requirements-test.txt
          pip install dist/xmlsec-$(python setup.py --version).tar.gz
      - name: Run tests
        run: |
          pytest -v --color=yes
      - name: Upload dist
        if: startsWith(github.ref, 'refs/tags/')
        env:
          TWINE_NON_INTERACTIVE: true
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_token }}
        run: |
          pip install twine
          twine upload dist/xmlsec-*.tar.gz
